- .github/workflows/deploy.yml
- appspec.yml
- infra/Dockerfile
- infra/docker-compose.yml
- scripts/start.sh
> [Infra] 백엔드 인프라 아키텍처 구축

- .github/workflows/deploy.yml
> [Infra] 백엔드 인프라 아키텍처 구축(1차 수정)

- src/main/resources/db/migration/mysql/V1__init.sql
- src/main/resources/db/migration/mysql/V2__add_oauth2_user_id_to_users.sql
- src/main/resources/db/migration/mysql/V3__remove_unique_constraint_from_place_name.sql
> [fix] Flyway 마이그레이션 파일 수정

- src/main/java/com/spoteditor/backend/config/oauth/dto/OauthAttributesUserMapper.java
- src/main/java/com/spoteditor/backend/user/entity/User.java
> [fix] OauthUserResolver 유저 생성시 Role 누락 해결

- src/main/java/com/spoteditor/backend/config/jwt/JwtFilter.java
- src/main/java/com/spoteditor/backend/config/jwt/JwtUtils.java
- src/main/java/com/spoteditor/backend/global/response/ErrorCode.java
- src/main/java/com/spoteditor/backend/global/response/GlobalExceptionHandler.java
- src/main/java/com/spoteditor/backend/user/service/UserTokenService.java
> [fix] JwtFilter 에서 Exception 덮어씌워지는 오류 해결

- src/main/java/com/spoteditor/backend/bookmark/controller/BookmarkApiController.java
- src/main/java/com/spoteditor/backend/config/cors/WebConfiguration.java
- src/main/java/com/spoteditor/backend/config/jwt/JwtFilter.java
- src/main/java/com/spoteditor/backend/config/swagger/BookmarkApiDocument.java
- src/main/java/com/spoteditor/backend/config/swagger/FollowApiDocument.java
- src/main/java/com/spoteditor/backend/config/swagger/NotificationApiDocument.java
- src/main/java/com/spoteditor/backend/config/swagger/PlaceApiDocument.java
- src/main/java/com/spoteditor/backend/config/swagger/PlaceImageApiDocument.java
- src/main/java/com/spoteditor/backend/config/swagger/SwaggerConfiguration.java
- src/main/java/com/spoteditor/backend/follow/controller/FollowApiController.java
- src/main/java/com/spoteditor/backend/image/controller/PlaceImageApiController.java
- src/main/java/com/spoteditor/backend/notification/controller/NotificationApiController.java
- src/main/java/com/spoteditor/backend/place/controller/PlaceApiController.java
> [docs] Swagger API 명세서 작업

- src/main/java/com/spoteditor/backend/config/util/CookieUtils.java
* #54 
[EC2에 요청시 쿠키가 안들어오는 문제](https://github.com/spoteditor/Spoteditor-Backend/wiki/EC2%EC%97%90-%EC%9A%94%EC%B2%AD%EC%8B%9C-%EC%BF%A0%ED%82%A4%EA%B0%80-%EC%95%88%EB%93%A4%EC%96%B4%EC%98%A4%EB%8A%94-%EB%AC%B8%EC%A0%9C)
> [fix] setSecure 속성 false로 변경

- src/main/java/com/spoteditor/backend/config/oauth/handler/OauthSuccessHandler.java
> [fix] 카카오 로그인 성공시 redirect주소 application.yml 설정 가능하게 변경

- src/test/java/com/spoteditor/backend/domain/user/entity/value/OauthProviderTest.java
> [test] OauthProvider 지원하는 Provider, 지원하지 않는 Provider 예외 테스트코드 추가

- src/main/java/com/spoteditor/backend/config/util/CookieUtils.java
- src/main/java/com/spoteditor/backend/global/health/HealthCheckController.java
* #66 
- 크로스 사이트 요청을 허용하므로 SameSite=None이고, 이 속성을 적용하려면 Secure=true 여야 한다.
> [feat] HTTPS 적용을 위한 healthCheck 추가

- src/main/java/com/spoteditor/backend/config/cors/WebConfiguration.java
> [fix] WebConfiguration에 프론트 주소 변경

- src/main/java/com/spoteditor/backend/config/cors/WebConfiguration.java
- src/main/java/com/spoteditor/backend/config/security/SecurityConfig.java
> [feat] 쿠키 저장을 위한 HTTPS 적용

- src/main/java/com/spoteditor/backend/follow/repository/FollowRepositoryCustom.java
- src/main/java/com/spoteditor/backend/follow/repository/FollowRepositoryCustomImpl.java
- src/main/java/com/spoteditor/backend/place/repository/PlaceRepositoryCustom.java
- src/main/java/com/spoteditor/backend/place/repository/PlaceRepositoryImpl.java
- src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryCustom.java
- src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
- src/main/java/com/spoteditor/backend/user/controller/UserPlaceLogController.java
- src/main/java/com/spoteditor/backend/user/controller/dto/UserResponse.java
- src/main/java/com/spoteditor/backend/user/service/UserServiceImpl.java
- src/main/java/com/spoteditor/backend/user/service/dto/UserResult.java
> [feat] 유저 메인페이지 기능

- src/main/java/com/spoteditor/backend/config/cors/WebConfiguration.java
> [TEST] 프론트엔드 테스트용 도메인 추가

- src/main/java/com/spoteditor/backend/config/cors/WebConfiguration.java
> [TEST] 프론트엔드 메인 도메인 추가

- docker-compose.yml
> [fix] Spring과 Redis 컨테이너 연결 오류 문제

- conf/slave.conf
- conf/slave1.conf
- conf/slave2.conf
- docker-compose.yml
> [fix] Spring과 Redis 컨테이너 연결 오류 문제2

- src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryCustom.java
- src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
- src/main/java/com/spoteditor/backend/user/controller/UserController.java
- src/main/java/com/spoteditor/backend/user/controller/UserPlaceLogController.java
- src/main/java/com/spoteditor/backend/user/controller/dto/UserResponse.java
> [feat] 메인페이지 기능 추가

- src/main/java/com/spoteditor/backend/placelog/service/PlaceLogServiceImpl.java
> [fix] 로그에 장소에 이미지 등록시 장소 중복 등록 문제 해결

- src/main/java/com/spoteditor/backend/config/jwt/JwtFilter.java
- src/main/java/com/spoteditor/backend/global/response/ErrorCode.java
- src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogController.java
- src/main/java/com/spoteditor/backend/placelog/service/PlaceLogService.java
- src/main/java/com/spoteditor/backend/placelog/service/PlaceLogServiceImpl.java
- src/main/java/com/spoteditor/backend/user/controller/UserPlaceLogController.java
> [fix] 비로그인 유저 서비스 사용을 위한 화이트리스트 추가

- src/main/java/com/spoteditor/backend/follow/controller/dto/FollowResponse.java
- src/main/java/com/spoteditor/backend/follow/entity/Follow.java
- src/main/java/com/spoteditor/backend/follow/repository/FollowRepositoryCustomImpl.java
- src/main/java/com/spoteditor/backend/follow/service/facade/FollowFacade.java
- src/main/java/com/spoteditor/backend/global/response/ErrorCode.java
- src/test/java/com/spoteditor/backend/config/QuerydslConfig.java
- src/test/java/com/spoteditor/backend/follow/entity/FollowTest.java
- src/test/java/com/spoteditor/backend/follow/repository/FollowRepositoryTest.java
- src/test/java/com/spoteditor/backend/follow/service/FollowServiceTest.java
* #42
- closed #42
- Presentation Layer에서 Mockito에 대한 학습이 좀 필요해보인다.
- 미진했던 Presentation Layer에 대한 부분은 #43 에서 보충할 예정입니다.
> [TEST] 다른 사용자를 팔로우할 수 있다. - 리팩토링 및 테스트 코드 보완

- src/main/java/com/spoteditor/backend/config/jwt/JwtFilter.java
> [fix] swagger 화이트리스트 추가

- docker-compose.yml
> [CHORE] 수정된 Docker-Compose 반영

- docker-compose.yml
* #105 
- redis node 헬스체크 로직 수정
- closed #105
> [chore] Docker compose Redis node 헬스체크 로직 변경

- src/main/java/com/spoteditor/backend/config/util/CookieUtils.java
> [fix] 로그아웃 쿠키 MaxAge미적용 문제 해결

- src/main/java/com/spoteditor/backend/config/jwt/JwtFilter.java
- src/main/java/com/spoteditor/backend/place/controller/dto/PlaceResponse.java
- src/main/java/com/spoteditor/backend/place/repository/PlaceRepositoryImpl.java
> [feat] API 정보 추가요청 반영

- src/main/java/com/spoteditor/backend/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/spoteditor/backend/bookmark/service/facade/BookmarkFacade.java
- src/main/java/com/spoteditor/backend/config/aop/AopForTransaction.java
- src/main/java/com/spoteditor/backend/config/aop/CustomSpringELParser.java
- src/main/java/com/spoteditor/backend/config/aop/DistributeLockAop.java
- src/main/java/com/spoteditor/backend/config/aop/DistributedLock.java
- src/main/java/com/spoteditor/backend/config/async/AsyncConfig.java
- src/main/java/com/spoteditor/backend/follow/controller/FollowApiController.java
- src/main/java/com/spoteditor/backend/follow/service/FollowService.java
- src/main/java/com/spoteditor/backend/follow/service/FollowServiceImpl.java
- src/main/java/com/spoteditor/backend/follow/service/facade/FollowFacade.java
- src/main/java/com/spoteditor/backend/notification/config/NotificationSubscriber.java
- src/main/java/com/spoteditor/backend/notification/controller/WebSocketHandler.java
- src/main/java/com/spoteditor/backend/notification/dto/NotificationDto.java
- src/main/java/com/spoteditor/backend/notification/dto/NotificationMessage.java
- src/main/java/com/spoteditor/backend/notification/event/NotificationEventDto.java
- src/main/java/com/spoteditor/backend/notification/handler/NotificationEventHandler.java
- src/main/java/com/spoteditor/backend/notification/service/NotificationService.java
- src/test/java/com/spoteditor/backend/follow/service/FollowServiceTest.java
> [TEST] 다른 사용자를 언팔로우할 수 있다. - 버그 개선 및 리팩토링

- docker-compose.yml
> Docker compose시 spring 컨테이너가 CREATED에서 넘어가지 않는 에러 수정
> [chore] Docker compose spring container 실행순서 변경

- src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogResponse.java
> [feat] PlaceLog 조회시 소유자 id 컬럼 추가

- src/main/java/com/spoteditor/backend/mapping/userplacelogmapping/repository/UserPlaceLogMappingRepositoryCustom.java
- src/main/java/com/spoteditor/backend/mapping/userplacelogmapping/repository/UserPlaceLogMappingRepositoryImpl.java
- src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogBookmarkController.java
> [feat] 로그 북마크 확인 기능

- src/main/java/com/spoteditor/backend/place/repository/PlaceRepositoryImpl.java
> [fix] PlaceRepository에 image join문 수정

- src/main/java/com/spoteditor/backend/follow/repository/FollowRepositoryCustom.java
- src/main/java/com/spoteditor/backend/follow/repository/FollowRepositoryCustomImpl.java
- src/main/java/com/spoteditor/backend/global/response/ErrorCode.java
- src/main/java/com/spoteditor/backend/user/controller/UserController.java
- src/main/java/com/spoteditor/backend/user/controller/dto/OtherUserResponse.java
- src/main/java/com/spoteditor/backend/user/service/UserService.java
- src/main/java/com/spoteditor/backend/user/service/UserServiceImpl.java
- src/main/java/com/spoteditor/backend/user/service/dto/OtherUserResult.java
> [feat] 프론트 response 컬럼 추가

- src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogController.java
- src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogListResponse.java
- src/main/java/com/spoteditor/backend/placelog/controller/dto/PlaceLogResponse.java
- src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
> [feat] 프론트 피드백내용 반영

- src/main/java/com/spoteditor/backend/placelog/entity/PlaceLog.java
- src/main/java/com/spoteditor/backend/user/service/UserServiceImpl.java
> [fix] 프론트 피드백내용 반영

- src/main/java/com/spoteditor/backend/config/jwt/JwtFilter.java
- src/main/java/com/spoteditor/backend/global/response/ErrorCode.java
- src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogSearchController.java
- src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryCustom.java
- src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
> [feat] 로그리스트 검색기능

- .github/workflows/check.yml
- src/main/java/com/spoteditor/backend/config/swagger/NotificationApiDocument.java
- src/main/java/com/spoteditor/backend/follow/service/FollowServiceImpl.java
- src/main/java/com/spoteditor/backend/notification/controller/NotificationApiController.java
- src/main/java/com/spoteditor/backend/notification/controller/dto/NotificationListDto.java
- src/main/java/com/spoteditor/backend/notification/dto/NotificationMessage.java
- src/main/java/com/spoteditor/backend/notification/repository/NotificationRepositoryCustom.java
- src/main/java/com/spoteditor/backend/notification/repository/NotificationRepositoryCustomImpl.java
> [FIX] 알림 API 버그 개선 내역

- src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
> [fix] Select구문에서 누락된 필드 추가

- src/main/java/com/spoteditor/backend/placelog/controller/PlaceLogSearchController.java
- src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryCustom.java
- src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
> [feat] 로그 검색 sigungu -> bname 변경

- README.md
> [docs] placeLogApi swagger 로그 수정기능 추가

- src/main/java/com/spoteditor/backend/placelog/repository/PlaceLogRepositoryImpl.java
> [feat] 로그 리스트 조회시 최신순 정렬

- src/main/java/com/spoteditor/backend/config/cors/WebConfiguration.java
> [feat] CORS 허용 URL을 application.yml에서 리스트로 받아 설정

- .github/workflows/deploy-onpremises.yml
- docker-compose.yml
> [CI/CD] 컨테이너 자동재부팅
